export const SIC_SECTION_TO_KEYWORDS: Record<string, string[]> = {
  A: ["agriculture", "farming", "forestry", "fishing"],
  B: ["mining", "quarrying", "extraction"],
  C: ["manufacturing", "production", "industrial"],
  D: ["energy", "electricity", "gas", "power"],
  E: ["water", "waste", "environment", "sewerage"],
  F: ["construction", "building", "infrastructure"],
  G: ["retail", "wholesale", "trade", "commerce"],
  H: ["transport", "logistics", "storage", "shipping"],
  I: ["hospitality", "food service", "accommodation", "tourism"],
  J: ["technology", "software", "digital", "telecom", "IT", "computing", "data"],
  K: ["finance", "insurance", "banking", "fintech"],
  L: ["real estate", "property"],
  M: ["scientific", "research", "engineering", "consulting", "professional"],
  N: ["administration", "support", "business services"],
  O: ["public administration", "defence", "social security"],
  P: ["education", "teaching", "training", "learning"],
  Q: ["health", "social work", "healthcare", "medical"],
  R: ["arts", "entertainment", "recreation", "creative", "culture"],
  S: ["community", "social", "charity", "membership"],
};

export const SIC_SECTION_NAMES: Record<string, string> = {
  A: "Agriculture, Forestry and Fishing",
  B: "Mining and Quarrying",
  C: "Manufacturing",
  D: "Electricity, Gas, Steam and Air Conditioning Supply",
  E: "Water Supply, Sewerage, Waste Management",
  F: "Construction",
  G: "Wholesale and Retail Trade",
  H: "Transportation and Storage",
  I: "Accommodation and Food Service Activities",
  J: "Information and Communication",
  K: "Financial and Insurance Activities",
  L: "Real Estate Activities",
  M: "Professional, Scientific and Technical Activities",
  N: "Administrative and Support Service Activities",
  O: "Public Administration and Defence",
  P: "Education",
  Q: "Human Health and Social Work Activities",
  R: "Arts, Entertainment and Recreation",
  S: "Other Service Activities",
};
